{{- if .Values.models.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local-ai.fullname" . }}-models
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
    io.localai/model_source: "1"
  {{- with .Values.annotations }}
  annotations:
    io.localai/target-directory: /models
  {{- end }}
data:
  {{- range $key, $data := .Values.models.configs}}
  {{ if or (hasSuffix $key ".yml") (hasSuffix $key ".yaml") }}{{ $key }}{{ else }}{{ $key }}.yaml{{ end }}: |-
    {{- $data | toYaml | nindent 4}}
  {{- end }}
{{- end }}